{% set name = "pydantic-settings" %}
{% set version = "2.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydantic_settings-{{ version }}.tar.gz
  sha256: 05d33003c74c2cd585de97b59eb17b6ed67181bc8a3ce594d74b5d24e4df7323

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - pydantic >=2.7.0
    - python-dotenv >=0.21.0

test:
  imports:
    - pydantic_settings
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Settings management using Pydantic
  home: https://github.com/pydantic/pydantic-settings
  dev_url: https://github.com/pydantic/pydantic-settings
  doc_url: https://docs.pydantic.dev/latest/usage/pydantic_settings/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
    - fhoehle
